### ISSUE TITLE
请教下如何配置ChatGPT-Next-Web

### ISSUE THREAD

**Issue by ciothepul** [tian-minghui/openai-style-api#31]
在同一服务器上启动了[openai-style-api](https://github.com/tian-minghui/openai-style-api)和[ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web)，openai-style-api没有问题，可以单独正常使用，但是到了ChatGPT-Next-Web上就一直报连接错误，原因是什么呢
![image](https://github.com/tian-minghui/openai-style-api/assets/136688448/4fd307f8-1a1b-48a9-9111-df46706da918)

docker-compose配置如下
```yaml
version: '3'

services:
  chatgpt-web:
    image: yidadaa/chatgpt-next-web
    ports:
      - 3000:3000
    environment:
      OPENAI_API_KEY: 7c7aa4a3549f12
      BASE_URL: http://azure-openai:8080
      CODE: ""
      HIDE_USER_API_KEY: 1
      HIDE_BALANCE_QUERY: 1
    depends_on:
      - azure-openai
    links:
      - azure-openai
    networks:
      - chatgpt-ns

  azure-openai:
    image: tianminghui/openai-style-api
    ports:
      - 8080:8080
    environment:
      - ADMIN-TOKEN=admin
    volumes:
      - ./model-config.json:/app/model-config.json
    networks:
      - chatgpt-ns

networks:
  chatgpt-ns:
    driver: bridge
```
